name: Build LaTeX document
on:
  push:
    branches:
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          ref: build
      - name: Merge main -> build
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: build
          github_token: ${{ github.token }}
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: proyecto.tex
          args: -pdf -f -file-line-error -interaction=nonstopmode
      - name: Upload PDF file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Upload compiled PDF
          file_pattern: 'proyecto.pdf'
